---
- name: Install packages
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - ruby
    - libpng-dev
    - libfontconfig-dev
    - python-pip
  tags: packages

- name: Create global .gitconfig with default user.name and user.email.
  sudo: no
  template: src=gconfig.j2 dest=/home/vagrant/.gitconfig force=no
  tags: git

- name: Install SASS
  sudo: yes
  gem: name=sass state=present user_install=no
  tags: css

- name: Install heroku-toolbelt
  include: 'heroku.yml'
  sudo: yes
  tags: heroku-toolbelt

- name: Install nodejs, npm, and npm packages
  include: node.yml
  tags: nodejs

- name: Create app directory for app
  sudo: no
  file: path=/vagrant/app state=directory
  tags: app

- name: Start in /vagrant directory when ssh
  lineinfile: dest=/home/vagrant/.bashrc regexp='^cd /vagrant/app$' line="cd /vagrant/app" state=present
  tags: .bashrc
