---
- name: Get the Node.js maintained repositories script
  get_url:
    url=https://deb.nodesource.com/setup_0.12
    dest=/tmp/nodesetup
    mode=0440
  sudo: yes
  tags: nodejs

- name: Add the Node.js maintained repositories to your Ubuntu package source list
  shell: /bin/bash /tmp/nodesetup
  sudo: yes
  tags: nodejs

- name: Install Node.js and npm
  apt: pkg=nodejs update-cache=yes
  sudo: yes
  tags: nodejs

- name: Install npm packages
  sudo: yes
  npm: name={{ item }} global=yes
  with_items:
    - npm
    - bower
    - grunt-cli
    - yo
    - generator-angular-fullstack
  tags: npm-global
